---
title: "Artist Collaboration in Billboard Hot 100"
output: 
  html_document:
    theme: readable
    toc: True
    thubnails: False
    highlight: default
    self_contained: False
    df_print: kable
    code_folding: hide
---


# Data

```{r setup, include=FALSE}
knitr::opts_chunk$set(
                      fig.width=25, 
                      fig.height=18,
                      message = FALSE,
                      warning = FALSE)
```



# Creating the graph
```{r}
library(tidygraph)
library(ggraph)
library(tidyverse)
library(gtools)
library(hrbrthemes)
library(lubridate)
library(igraph)
library(RColorBrewer)
library(here)

# Reading-in and cleaning data

x <- read_csv(here("data/input/billboardHot100_1999-2019.csv"))


y <- x %>%
  distinct(Artists, Name, .keep_all = TRUE) %>%
  filter(year(Week) > 2010) %>%
  filter(Artists != "Jack, Jack") %>%
  mutate(
    Artists = str_replace(Artists, "Tyler, The Creator", "Tyler The Creator"),
    Genre = str_replace(Genre, "Hip-Hop", "Rap"),
    Genre = str_replace(Genre, "R&;B", "R&B"),
    list_of_artists = str_split(Artists, ", "),
    list_of_genres = str_split(Genre, ",")
  ) %>%
  replace_na(list(Peak.position = -1)) %>%
  mutate(
    Peak.position = if_else(Peak.position == -1, Weekly.rank, Peak.position),
    weight = 100 - Peak.position
  )

write_csv(y,here("data/output/billboard_clean.csv"))

# Assigning a genre to an artist based on the genre of the songs they appear on
artists <- distinct(as_tibble(unlist(y$list_of_artists)))

genres <- unnest(y, col = list_of_genres) %>%
  count(list_of_genres) %>%
  arrange(desc(n))
genres <- genres$list_of_genres

artist_genre <- unnest_longer(y, col = list_of_genres) %>%
  unnest_longer(col = list_of_artists) %>%
  group_by(list_of_artists, list_of_genres) %>%
  count() %>%
  ungroup() %>%
  group_by(list_of_artists) %>%
  slice_max(n, n = 1) %>%
  arrange(factor(list_of_genres, levels = genres)) %>%
  slice_head(n = 1)

artist_genre$list_of_genres <- fct_lump_n(artist_genre$list_of_genres, 6)
artists <- left_join(artists, artist_genre, c("value" = "list_of_artists"))
artists <- artists[1:2]

# Constructing the graph
y <- y %>% filter(lengths(list_of_artists) > 1)
weights <- map2(y$weight, y$list_of_artists, ~ rep(.x, choose(length(.y), 2)))
name <- map2(y$Name, y$list_of_artists, ~ rep(.x, choose(length(.y), 2)))
genre <- map2(y$Genre, y$list_of_artists, ~ rep(.x, choose(length(.y), 2)))
edges <- map(y$list_of_artists, ~ combinations(length(.x), 2, .x))
edges <- reduce(edges, rbind)
edges <- as_tibble(edges)
edges$weights <- reduce(weights, c)
edges$Name <- reduce(name, c)
edges$Genre <- reduce(genre,c)

graph <- tbl_graph(nodes = artists, 
                   edges = edges, 
                   node_key = c("V1", "V2"), 
                   directed = F) 
graph <- discard(to_components(graph), ~ gorder(.x) < 5) %>%
  bind_graphs() %>% 
  activate(nodes) %>%
  mutate(
    degr = centrality_degree(),
    degr_weighted = centrality_degree(weights = weights)
  )

# Saving the graph 
saveRDS(graph,file=here("data/output/graph.RDS"))
```

# Graph analysis

```{r}
# Graph analysis
as_tibble(graph) %>% slice_max(degr,n=5)
as_tibble(graph) %>% slice_max(degr_weighted, n=5)
```

# To do

- 

- 

- 

# Visualising the graph

## All genres

```{r}
# Function to plot the graph
plot_graph <- function(graph, plot_subtitle) {
  ggraph(graph) +
    geom_edge_link0(aes(width = 100 - weights),
                    edge_colour = "grey66", 
                    show.legend = FALSE) +
    geom_node_point(aes(size = degr, 
                        color = list_of_genres)) +
    geom_node_text(aes(filter = (degr > 3), 
                       label = value),
      family = "Roboto Condensed", repel = TRUE, size = 8.5
    ) +
    theme_graph(base_size = 30,
                title_size = 40, 
                subtitle_size = 36) +
    scale_size(range = c(10, 20)) +
    scale_edge_width_continuous(range = c(0.1, 2)) +
    scale_color_brewer(
      "Genre",
      palette = "Set2",
      limits = unique(artists$list_of_genres),
      guide = guide_legend(
        override.aes = list(size = 8),
        nrow = 1, title.position = "top"
      )
    ) +
    guides(size = "none") +
    theme(legend.position = "bottom") +
    labs(title = "Artist collaborations", 
         subtitle = plot_subtitle)
}
```


```{r}
plot_graph(graph,"In songs of all genres")
```


## Pop songs

```{r}
# Filtering out only a single genre
subset_genre <- function(graph, genre_filter) {
  graph <- graph %>%
    activate(edges) %>%
    filter(str_detect(Genre, genre_filter))
  
  graph <- discard(to_components(graph), ~ gorder(.x) < 5) %>%
    bind_graphs()
  
  graph
}

plot_graph(subset_genre(graph,"Pop"),"In pop songs only") 
```

## Rap songs

```{r}
plot_graph(subset_genre(graph,"Hip-Hop|Rap|Trap"),"In rap songs only")
```



## Visualising clusters

```{r}
# Calculate the clusters
graph <- graph %>%
  mutate(clust = as_factor(tidygraph::group_louvain(weights = weights))) %>%
  morph(to_split, clust) %>%
  activate(nodes) %>%
  mutate(main = ifelse(centrality_degree() > max(centrality_degree())-1, value, "")) %>%
  unmorph()


myColors <- c(brewer.pal(13, "Paired"), "black")
names(myColors) <- levels(as_tibble(graph)$clust)



ggraph(graph, layout = "kk") +
  geom_edge_link0(aes(width = 100 - weights), edge_colour = "grey66") +
  geom_node_point(aes(size = degr, color = clust)) +
  geom_node_text(aes(label = main), family = "Roboto Condensed", repel = FALSE, size = 8.5) +
  theme_graph(base_size = 30, title_size = 40, subtitle_size = 36) +
  scale_size(range = c(10, 20)) +
  scale_edge_width_continuous(range = c(0.1, 1.5)) +
  scale_color_manual(values = myColors) +
  theme(legend.position = "none") +
  labs(title = "Artist collaboration", subtitle = "Billboard Hot 100 songs")

plot_clusters <- function(graph, xlimit, ylimit, groups) {
  ggraph(graph, layout = "kk") +
    geom_edge_link0(aes(width = 100 - weights), edge_colour = "grey66") +
    geom_node_text(aes(filter = as.numeric(clust) %in% groups, label = value),
      family = "Roboto Condensed", repel = TRUE, size = 8.5) +
    geom_node_point(aes(filter = as.numeric(clust) %in% groups, size = degr, color = clust)) +
    geom_node_point(aes(filter=!(as.numeric(clust) %in% groups),size=degr),
                  alpha=0.5,color="grey") +
    theme_graph(base_size = 30, title_size = 40, subtitle_size = 36) +
    scale_size(range = c(10, 20)) +
    scale_edge_width_continuous(range = c(0.1, 1.5)) +
    scale_color_manual(values = myColors) +
    theme(legend.position = "none") +
    labs(title = "Artist collaboration", subtitle = "Billboard Hot 100 songs") +
    xlim(xlimit) +
    ylim(ylimit)
}
```



```{r}
plot_clusters(graph,c(-4,3),c(0,8),c(1:13))
```


```{r}
plot_clusters(graph,c(0,6),c(-4,3),c(1:13))
```



```{r}
plot_clusters(graph,c(-3,2),c(-5,0.5),c(1:13))
```



# Session info

```{r}
devtools::session_info()
```

